const categoriesResponseMock = {
  id: 'MLA352679',
  name: 'Smartwatch',
  picture: null,
  permalink: null,
  total_items_in_this_category: 5070,
  path_from_root: [
    {
      id: 'MLA1051',
      name: 'Celulares y Teléfonos',
    },
    {
      id: 'MLA417704',
      name: 'Smartwatches y Accesorios',
    },
    {
      id: 'MLA352679',
      name: 'Smartwatch',
    },
  ],
  children_categories: [],
  attribute_types: 'variations',
  settings: {
    adult_content: false,
    buying_allowed: true,
    buying_modes: [
      'buy_it_now',
      'auction',
    ],
    catalog_domain: 'MLA-SMARTWATCHES',
    coverage_areas: 'not_allowed',
    currencies: [
      'ARS',
    ],
    fragile: false,
    immediate_payment: 'required',
    item_conditions: [
      'not_specified',
      'used',
      'new',
    ],
    items_reviews_allowed: false,
    listing_allowed: true,
    max_description_length: 50000,
    max_pictures_per_item: 12,
    max_pictures_per_item_var: 10,
    max_sub_title_length: 70,
    max_title_length: 60,
    maximum_price: null,
    minimum_price: 22,
    mirror_category: 'MLA399230',
    mirror_master_category: null,
    mirror_slave_categories: [
      'MLA399230',
    ],
    price: 'required',
    reservation_allowed: 'not_allowed',
    restrictions: [],
    rounded_address: false,
    seller_contact: 'not_allowed',
    shipping_modes: [
      'custom',
      'me2',
      'me1',
      'not_specified',
    ],
    shipping_options: [
      'custom',
      'carrier',
    ],
    shipping_profile: 'optional',
    show_contact_information: false,
    simple_shipping: 'optional',
    stock: 'required',
    sub_vertical: 'cellphones_telephones',
    subscribable: false,
    tags: [],
    vertical: 'consumer_electronics',
    vip_subdomain: 'articulo',
    buyer_protection_programs: [
      'delivered',
      'undelivered',
    ],
    status: 'enabled',
  },
  meta_categ_id: null,
  attributable: false,
  date_created: '2018-04-25T08:12:56.000Z',
};

export default categoriesResponseMock;
