const itemsResponseMock = {
  id: 'MLA715635100',
  site_id: 'MLA',
  title: 'Xiaomi Mi Band 4 Smartwatch Reloj Inteligente Version Global Caja Sellada Original Smart Supera Band 3',
  subtitle: null,
  seller_id: 257077964,
  category_id: 'MLA352679',
  official_store_id: null,
  price: 2979,
  base_price: 2979,
  original_price: 3549,
  currency_id: 'ARS',
  initial_quantity: 12206,
  available_quantity: 150,
  sold_quantity: 5000,
  sale_terms: [
    {
      id: 'WARRANTY_TIME',
      name: 'Tiempo de garantía',
      value_id: null,
      value_name: '6.0 meses',
      value_struct: {
        number: 6,
        unit: 'meses',
      },
      values: [
        {
          id: null,
          name: '6.0 meses',
          struct: {
            number: 6,
            unit: 'meses',
          },
        },
      ],
    },
    {
      id: 'WARRANTY_TYPE',
      name: 'Tipo de garantía',
      value_id: '2230280',
      value_name: 'Garantía del vendedor',
      value_struct: null,
      values: [
        {
          id: '2230280',
          name: 'Garantía del vendedor',
          struct: null,
        },
      ],
    },
  ],
  buying_mode: 'buy_it_now',
  listing_type_id: 'gold_special',
  start_time: '2018-03-29T13:47:16.000Z',
  stop_time: '2040-05-25T11:19:53.000Z',
  condition: 'new',
  permalink: 'https://articulo.mercadolibre.com.ar/MLA-715635100-xiaomi-mi-band-4-smartwatch-reloj-inteligente-version-global-caja-sellada-original-smart-supera-band-3-_JM',
  thumbnail: 'http://mla-s1-p.mlstatic.com/916416-MLA31293979258_072019-I.jpg',
  secure_thumbnail: 'https://mla-s1-p.mlstatic.com/916416-MLA31293979258_072019-I.jpg',
  pictures: [
    {
      id: '916416-MLA31293979258_072019',
      url: 'http://mla-s1-p.mlstatic.com/916416-MLA31293979258_072019-O.jpg',
      secure_url: 'https://mla-s1-p.mlstatic.com/916416-MLA31293979258_072019-O.jpg',
      size: '500x500',
      max_size: '1200x1200',
      quality: '',
    },
    {
      id: '998628-MLA31293967679_072019',
      url: 'http://mla-s1-p.mlstatic.com/998628-MLA31293967679_072019-O.jpg',
      secure_url: 'https://mla-s1-p.mlstatic.com/998628-MLA31293967679_072019-O.jpg',
      size: '500x500',
      max_size: '1200x1200',
      quality: '',
    },
    {
      id: '877174-MLA31118244045_062019',
      url: 'http://mla-s1-p.mlstatic.com/877174-MLA31118244045_062019-O.jpg',
      secure_url: 'https://mla-s1-p.mlstatic.com/877174-MLA31118244045_062019-O.jpg',
      size: '500x500',
      max_size: '598x598',
      quality: '',
    },
    {
      id: '740318-MLA31293889400_072019',
      url: 'http://mla-s1-p.mlstatic.com/740318-MLA31293889400_072019-O.jpg',
      secure_url: 'https://mla-s1-p.mlstatic.com/740318-MLA31293889400_072019-O.jpg',
      size: '500x265',
      max_size: '1200x636',
      quality: '',
    },
    {
      id: '768685-MLA31293914604_072019',
      url: 'http://mla-s1-p.mlstatic.com/768685-MLA31293914604_072019-O.jpg',
      secure_url: 'https://mla-s1-p.mlstatic.com/768685-MLA31293914604_072019-O.jpg',
      size: '500x333',
      max_size: '1200x800',
      quality: '',
    },
    {
      id: '812759-MLA31293889402_072019',
      url: 'http://mla-s1-p.mlstatic.com/812759-MLA31293889402_072019-O.jpg',
      secure_url: 'https://mla-s1-p.mlstatic.com/812759-MLA31293889402_072019-O.jpg',
      size: '500x333',
      max_size: '1200x800',
      quality: '',
    },
  ],
  video_id: 'rLFh54ifUuY',
  descriptions: [
    {
      id: 'MLA715635100-1623327014',
    },
  ],
  accepts_mercadopago: true,
  non_mercado_pago_payment_methods: [],
  shipping: {
    mode: 'me2',
    free_methods: [
      {
        id: 73328,
        rule: {
          default: true,
          free_mode: 'country',
          free_shipping_flag: true,
          value: null,
        },
      },
    ],
    tags: [
      'self_service_in',
      'mandatory_free_shipping',
    ],
    dimensions: null,
    local_pick_up: false,
    free_shipping: true,
    logistic_type: 'fulfillment',
    store_pick_up: false,
  },
  international_delivery_mode: 'none',
  seller_address: {
    city: {
      id: 'TUxBQkNIQTM5NjBa',
      name: 'Chacarita',
    },
    state: {
      id: 'AR-C',
      name: 'Capital Federal',
    },
    country: {
      id: 'AR',
      name: 'Argentina',
    },
    search_location: {
      neighborhood: {
        id: 'TUxBQkNIQTM5NjBa',
        name: 'Chacarita',
      },
      city: {
        id: 'TUxBQ0NBUGZlZG1sYQ',
        name: 'Capital Federal',
      },
      state: {
        id: 'TUxBUENBUGw3M2E1',
        name: 'Capital Federal',
      },
    },
    latitude: -34.596504,
    longitude: -58.45042,
    id: 1099779674,
  },
  seller_contact: null,
  location: {},
  geolocation: {
    latitude: -34.596504,
    longitude: -58.45042,
  },
  coverage_areas: [],
  attributes: [
    {
      id: 'AGE_GROUP',
      name: 'Edad',
      value_id: '-1',
      value_name: null,
      value_struct: null,
      values: [
        {
          id: '-1',
          name: null,
          struct: null,
        },
      ],
      attribute_group_id: '',
      attribute_group_name: '',
    },
    {
      id: 'GENDER',
      name: 'Género',
      value_id: '110461',
      value_name: 'Sin género',
      value_struct: null,
      values: [
        {
          id: '110461',
          name: 'Sin género',
          struct: null,
        },
      ],
      attribute_group_id: '',
      attribute_group_name: '',
    },
    {
      id: 'MAIN_COLOR',
      name: 'Color principal',
      value_id: '2450295',
      value_name: 'Negro',
      value_struct: null,
      values: [
        {
          id: '2450295',
          name: 'Negro',
          struct: null,
        },
      ],
      attribute_group_id: '',
      attribute_group_name: '',
    },
    {
      id: 'ALPHANUMERIC_MODEL',
      name: 'Modelo alfanumérico',
      value_id: null,
      value_name: 'MIBAND4',
      value_struct: null,
      values: [
        {
          id: null,
          name: 'MIBAND4',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'BATTERY_LIFE',
      name: 'Duración de la batería',
      value_id: '7261468',
      value_name: '20 días',
      value_struct: {
        number: 20,
        unit: 'días',
      },
      values: [
        {
          id: '7261468',
          name: '20 días',
          struct: {
            number: 20,
            unit: 'días',
          },
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'BRAND',
      name: 'Marca',
      value_id: '59387',
      value_name: 'Xiaomi',
      value_struct: null,
      values: [
        {
          id: '59387',
          name: 'Xiaomi',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'DISPLAY_SIZE',
      name: 'Tamaño de la pantalla',
      value_id: '7254398',
      value_name: '0.78 in',
      value_struct: {
        number: 0.78,
        unit: 'in',
      },
      values: [
        {
          id: '7254398',
          name: '0.78 in',
          struct: {
            number: 0.78,
            unit: 'in',
          },
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'DISPLAY_TYPE',
      name: 'Tipo de pantalla',
      value_id: '179608',
      value_name: 'Táctil',
      value_struct: null,
      values: [
        {
          id: '179608',
          name: 'Táctil',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'INTERNAL_MEMORY',
      name: 'Memoria interna',
      value_id: '75256',
      value_name: '16 MB',
      value_struct: {
        number: 16,
        unit: 'MB',
      },
      values: [
        {
          id: '75256',
          name: '16 MB',
          struct: {
            number: 16,
            unit: 'MB',
          },
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'IS_WATERPROOF',
      name: 'Es a prueba de agua',
      value_id: '242085',
      value_name: 'Sí',
      value_struct: null,
      values: [
        {
          id: '242085',
          name: 'Sí',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'IS_WATER_RESISTANT',
      name: 'Es resistente al agua',
      value_id: '242085',
      value_name: 'Sí',
      value_struct: null,
      values: [
        {
          id: '242085',
          name: 'Sí',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'ITEM_CONDITION',
      name: 'Condición del ítem',
      value_id: '2230284',
      value_name: 'Nuevo',
      value_struct: null,
      values: [
        {
          id: '2230284',
          name: 'Nuevo',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'LINE',
      name: 'Línea',
      value_id: '8824122',
      value_name: 'Mi Band',
      value_struct: null,
      values: [
        {
          id: '8824122',
          name: 'Mi Band',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'MAX_RESOLUTION',
      name: 'Resolución máxima',
      value_id: '7478997',
      value_name: '120 x 240 px',
      value_struct: null,
      values: [
        {
          id: '7478997',
          name: '120 x 240 px',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'MAX_WATER_RESISTANCE_DEPTH',
      name: 'Profundidad máxima de resistencia al agua',
      value_id: '7128152',
      value_name: '50 m',
      value_struct: {
        number: 50,
        unit: 'm',
      },
      values: [
        {
          id: '7128152',
          name: '50 m',
          struct: {
            number: 50,
            unit: 'm',
          },
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'MODEL',
      name: 'Modelo',
      value_id: '7328635',
      value_name: 'Mi Band 4',
      value_struct: null,
      values: [
        {
          id: '7328635',
          name: 'Mi Band 4',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'SMARTWATCH_FUNCTIONS',
      name: 'Funciones',
      value_id: null,
      value_name: 'Monitor de frecuencia cardíaca,Calorias quemadas,Cronómetro,leer mensajes,notifica llamadas,Seguimiento por ejercicio',
      value_struct: null,
      values: [
        {
          id: null,
          name: 'Monitor de frecuencia cardíaca',
          struct: null,
        },
        {
          id: null,
          name: 'Calorias quemadas',
          struct: null,
        },
        {
          id: '182485',
          name: 'Cronómetro',
          struct: null,
        },
        {
          id: null,
          name: 'leer mensajes',
          struct: null,
        },
        {
          id: null,
          name: 'notifica llamadas',
          struct: null,
        },
        {
          id: null,
          name: 'Seguimiento por ejercicio',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'SMARTWATCH_VERSION',
      name: 'Versión',
      value_id: null,
      value_name: '4',
      value_struct: null,
      values: [
        {
          id: null,
          name: '4',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'WITH_BLUETOOTH',
      name: 'Con Bluetooth',
      value_id: '242085',
      value_name: 'Sí',
      value_struct: null,
      values: [
        {
          id: '242085',
          name: 'Sí',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      id: 'WITH_NFC',
      name: 'Con NFC',
      value_id: '242084',
      value_name: 'No',
      value_struct: null,
      values: [
        {
          id: '242084',
          name: 'No',
          struct: null,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
  ],
  warnings: [],
  listing_source: '',
  variations: [
    {
      id: 39609073880,
      price: 2979,
      attribute_combinations: [
        {
          id: 'CASE_COLOR',
          name: 'Color de la caja',
          value_id: '52049',
          value_name: 'Negro',
          value_struct: null,
          values: [
            {
              id: '52049',
              name: 'Negro',
              struct: null,
            },
          ],
        },
        {
          id: 'BAND_COLOR',
          name: 'Color de la malla',
          value_id: '52049',
          value_name: 'Negro',
          value_struct: null,
          values: [
            {
              id: '52049',
              name: 'Negro',
              struct: null,
            },
          ],
        },
        {
          id: 'BEZEL_COLOR',
          name: 'Color del bisel',
          value_id: '52049',
          value_name: 'Negro',
          value_struct: null,
          values: [
            {
              id: '52049',
              name: 'Negro',
              struct: null,
            },
          ],
        },
      ],
      available_quantity: 150,
      sold_quantity: 5000,
      sale_terms: [],
      picture_ids: [
        '916416-MLA31293979258_072019',
        '998628-MLA31293967679_072019',
        '877174-MLA31118244045_062019',
        '740318-MLA31293889400_072019',
        '768685-MLA31293914604_072019',
        '812759-MLA31293889402_072019',
      ],
      catalog_product_id: 'MLA14786768',
    },
  ],
  status: 'active',
  sub_status: [],
  tags: [
    'loyalty_discount_eligible',
    'brand_verified',
    'good_quality_picture',
    'good_quality_thumbnail',
    'immediate_payment',
    'cart_eligible',
  ],
  warranty: 'Garantía del vendedor: 6.0 meses',
  catalog_product_id: 'MLA14786767',
  domain_id: 'MLA-SMARTWATCHES',
  parent_item_id: null,
  differential_pricing: null,
  deal_ids: [],
  automatic_relist: false,
  date_created: '2018-03-29T13:47:16.000Z',
  last_updated: '2020-08-06T22:07:28.000Z',
  health: 0.9,
  catalog_listing: false,
};

export default itemsResponseMock;
