const searchResponseMock = {
  site_id: 'MLA',
  query: 'chromecast',
  paging: {
    total: 315,
    offset: 0,
    limit: 4,
    primary_results: 315,
  },
  results: [
    {
      id: 'MLA832079323',
      site_id: 'MLA',
      title: ' Google Chromecast 3rd Generation Full Hd Carbón Con Memoria Ram De 512mb',
      seller: {
        id: 96270679,
        permalink: 'http://perfil.mercadolibre.com.ar/LAMEJORSOLUCION',
        registration_date: '2006-07-12T14:29:02.000-04:00',
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          'normal',
          'user_info_verified',
          'eshop',
          'medium_seller',
          'messages_as_seller',
          'messages_as_buyer',
        ],
        eshop: {
          nick_name: 'LAMEJORSOLUCION',
          eshop_rubro: null,
          eshop_id: 25493,
          eshop_locations: [],
          site_id: 'MLA',
          eshop_logo_url: 'http://resources.mlstatic.com/eshops/96270679.png',
          eshop_status_id: 1,
          seller: 96270679,
          eshop_experience: 0,
        },
        seller_reputation: {
          transactions: {
            total: 80051,
            canceled: 4004,
            period: 'historic',
            ratings: {
              negative: 0.02,
              positive: 0.96,
              neutral: 0.02,
            },
            completed: 76047,
          },
          power_seller_status: 'platinum',
          metrics: {
            claims: {
              rate: 0,
              excluded: {
                real_rate: 0.0207,
                real_value: 110,
              },
              value: 0,
              period: '3 months',
            },
            delayed_handling_time: {
              rate: 0,
              excluded: {
                real_rate: 0.0129,
                real_value: 62,
              },
              value: 0,
              period: '3 months',
            },
            sales: {
              period: '3 months',
              completed: 5018,
            },
            cancellations: {
              rate: 0,
              excluded: {
                real_rate: 0.0052,
                real_value: 28,
              },
              value: 0,
              period: '3 months',
            },
          },
          protection_end_date: '2020-08-27T00:00:00.000-04:00',
          real_level: 'yellow',
          level_id: '5_green',
        },
        address: {
          zip_code: '1071',
          address: 'Tacuari 239',
          state: 'AR-C',
          city: 'Capital Federal',
        },
      },
      price: 5030,
      currency_id: 'ARS',
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: 'buy_it_now',
      listing_type_id: 'gold_special',
      stop_time: '2039-12-22T04:00:00.000Z',
      condition: 'new',
      permalink: 'https://www.mercadolibre.com.ar/google-chromecast-3rd-generation-full-hd-carbon-con-memoria-ram-de-512mb/p/MLA13841393',
      thumbnail: 'http://mla-s2-p.mlstatic.com/620605-MLA32691559317_102019-I.jpg',
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 713.3,
        rate: 70.17,
        currency_id: 'ARS',
      },
      address: {
        state_id: 'AR-C',
        state_name: 'Capital Federal',
        city_id: null,
        city_name: 'Capital Federal',
      },
      shipping: {
        free_shipping: true,
        mode: 'me2',
        tags: [
          'self_service_in',
          'mandatory_free_shipping',
        ],
        logistic_type: 'cross_docking',
        store_pick_up: false,
      },
      seller_address: {
        id: '',
        comment: '',
        address_line: '',
        zip_code: '',
        country: {
          id: 'AR',
          name: 'Argentina',
        },
        state: {
          id: 'AR-C',
          name: 'Capital Federal',
        },
        city: {
          id: null,
          name: 'Capital Federal',
        },
        latitude: '',
        longitude: '',
      },
      attributes: [
        {
          attribute_group_id: 'OTHERS',
          value_id: null,
          value_name: 'chromecast3',
          values: [
            {
              name: 'chromecast3',
              struct: null,
              source: 3376461333454861,
              id: null,
            },
          ],
          attribute_group_name: 'Otros',
          source: 3376461333454861,
          id: 'ALPHANUMERIC_MODEL',
          name: 'Modelo alfanumérico',
          value_struct: null,
        },
        {
          id: 'BRAND',
          value_id: '52701',
          value_name: 'Google',
          values: [
            {
              id: '52701',
              name: 'Google',
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          name: 'Marca',
          value_struct: null,
          source: 1,
        },
        {
          value_id: '2230284',
          value_name: 'Nuevo',
          values: [
            {
              name: 'Nuevo',
              struct: null,
              source: 1,
              id: '2230284',
            },
          ],
          id: 'ITEM_CONDITION',
          value_struct: null,
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          source: 1,
          name: 'Condición del ítem',
        },
        {
          value_name: 'Chromecast',
          source: 1505,
          values: [
            {
              name: 'Chromecast',
              struct: null,
              source: 1505,
              id: null,
            },
          ],
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          id: 'LINE',
          name: 'Línea',
          value_id: null,
          value_struct: null,
        },
        {
          attribute_group_name: 'Otros',
          value_id: '7807620',
          value_name: 'Chromecast 3rd Generation',
          attribute_group_id: 'OTHERS',
          values: [
            {
              struct: null,
              source: 1,
              id: '7807620',
              name: 'Chromecast 3rd Generation',
            },
          ],
          source: 1,
          id: 'MODEL',
          name: 'Modelo',
          value_struct: null,
        },
      ],
      original_price: null,
      category_id: 'MLA352001',
      official_store_id: null,
      domain_id: 'MLA-STREAMING_MEDIA_DEVICES',
      catalog_product_id: 'MLA13841393',
      tags: [
        'brand_verified',
        'good_quality_picture',
        'good_quality_thumbnail',
        'loyalty_discount_eligible',
        'immediate_payment',
        'cart_eligible',
        'shipping_guaranteed',
      ],
      catalog_listing: true,
    },
    {
      id: 'MLA832082627',
      site_id: 'MLA',
      title: ' Google Chromecast 2nd Generation Full Hd 256mb Negro Con Memoria Ram De 512mb',
      seller: {
        id: 70470402,
        permalink: 'http://perfil.mercadolibre.com.ar/COOL-TECH--',
        registration_date: '2011-09-26T22:25:16.000-04:00',
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          'normal',
          'user_info_verified',
          'credits_profile',
          'eshop',
          'messages_as_seller',
          'messages_as_buyer',
        ],
        eshop: {
          nick_name: 'COOL-TECH--',
          eshop_rubro: null,
          eshop_id: 241087,
          eshop_locations: [],
          site_id: 'MLA',
          eshop_logo_url: 'http://resources.mlstatic.com/eshops/70470402v4973c7.png',
          eshop_status_id: 1,
          seller: 70470402,
          eshop_experience: 0,
        },
        seller_reputation: {
          transactions: {
            total: 11536,
            canceled: 239,
            period: 'historic',
            ratings: {
              negative: 0.01,
              positive: 0.98,
              neutral: 0.01,
            },
            completed: 11297,
          },
          power_seller_status: 'platinum',
          metrics: {
            claims: {
              rate: 0.0088,
              value: 5,
              period: '3 months',
            },
            delayed_handling_time: {
              rate: 0,
              value: 0,
              period: '3 months',
            },
            sales: {
              period: '3 months',
              completed: 542,
            },
            cancellations: {
              rate: 0,
              value: 2,
              period: '3 months',
            },
          },
          level_id: '5_green',
        },
        address: {
          zip_code: '1048',
          address: 'lavalle 1578',
          state: 'AR-C',
          city: 'San Nicolás',
        },
      },
      price: 6999,
      currency_id: 'ARS',
      available_quantity: 500,
      sold_quantity: 250,
      buying_mode: 'buy_it_now',
      listing_type_id: 'gold_special',
      stop_time: '2040-04-04T05:24:07.000Z',
      condition: 'new',
      permalink: 'https://www.mercadolibre.com.ar/google-chromecast-2nd-generation-full-hd-256mb-negro-con-memoria-ram-de-512mb/p/MLA6125039',
      thumbnail: 'http://mla-s2-p.mlstatic.com/673013-MLA32691559312_102019-I.jpg',
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 992.52,
        rate: 70.17,
        currency_id: 'ARS',
      },
      address: {
        state_id: 'AR-C',
        state_name: 'Capital Federal',
        city_id: 'TUxBQlNBTjgzMjRa',
        city_name: 'San Nicolás',
      },
      shipping: {
        free_shipping: true,
        mode: 'me2',
        tags: [
          'self_service_out',
          'mandatory_free_shipping',
        ],
        logistic_type: 'cross_docking',
        store_pick_up: false,
      },
      seller_address: {
        id: '',
        comment: '',
        address_line: '',
        zip_code: '',
        country: {
          id: 'AR',
          name: 'Argentina',
        },
        state: {
          id: 'AR-C',
          name: 'Capital Federal',
        },
        city: {
          id: 'TUxBQlNBTjgzMjRa',
          name: 'San Nicolás',
        },
        latitude: '',
        longitude: '',
      },
      attributes: [
        {
          value_name: 'Chromecast 2',
          values: [
            {
              struct: null,
              source: 2187367636293270,
              id: null,
              name: 'Chromecast 2',
            },
          ],
          attribute_group_id: 'OTHERS',
          source: 2187367636293270,
          id: 'ALPHANUMERIC_MODEL',
          name: 'Modelo alfanumérico',
          attribute_group_name: 'Otros',
          value_id: null,
          value_struct: null,
        },
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '52701',
          attribute_group_name: 'Otros',
          source: 1,
          value_name: 'Google',
          value_struct: null,
          values: [
            {
              id: '52701',
              name: 'Google',
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: 'OTHERS',
        },
        {
          value_name: 'Nuevo',
          values: [
            {
              id: '2230284',
              name: 'Nuevo',
              struct: null,
              source: 1,
            },
          ],
          id: 'ITEM_CONDITION',
          name: 'Condición del ítem',
          value_id: '2230284',
          value_struct: null,
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          source: 1,
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_struct: null,
          attribute_group_id: 'OTHERS',
          source: 1,
          value_id: '7807621',
          value_name: 'Chromecast 2nd Generation',
          values: [
            {
              source: 1,
              id: '7807621',
              name: 'Chromecast 2nd Generation',
              struct: null,
            },
          ],
          attribute_group_name: 'Otros',
        },
      ],
      original_price: null,
      category_id: 'MLA352001',
      official_store_id: null,
      domain_id: 'MLA-STREAMING_MEDIA_DEVICES',
      catalog_product_id: 'MLA6125039',
      tags: [
        'brand_verified',
        'good_quality_picture',
        'good_quality_thumbnail',
        'loyalty_discount_eligible',
        'immediate_payment',
        'cart_eligible',
        'shipping_guaranteed',
      ],
      catalog_listing: true,
    },
    {
      id: 'MLA856774527',
      site_id: 'MLA',
      title: 'Google Chromecast 3ra Generacion 2018 Smart Tv Bulk Sin Caja',
      seller: {
        id: 309453406,
        permalink: 'http://perfil.mercadolibre.com.ar/BAZA+10',
        registration_date: '2018-03-21T15:00:14.000-04:00',
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          'normal',
          'user_info_verified',
          'mshops',
          'credits_profile',
          'eshop',
          'messages_as_seller',
          'messages_as_buyer',
        ],
        eshop: {
          nick_name: 'BAZA 10',
          eshop_rubro: null,
          eshop_id: 317770,
          eshop_locations: [],
          site_id: 'MLA',
          eshop_logo_url: 'http://resources.mlstatic.com/eshops/309453406v73ad9f.png',
          eshop_status_id: 1,
          seller: 309453406,
          eshop_experience: 0,
        },
        seller_reputation: {
          transactions: {
            total: 30060,
            canceled: 2405,
            period: 'historic',
            ratings: {
              negative: 0.04,
              positive: 0.94,
              neutral: 0.02,
            },
            completed: 27655,
          },
          power_seller_status: 'platinum',
          metrics: {
            claims: {
              rate: 0,
              excluded: {
                real_rate: 0.0168,
                real_value: 185,
              },
              value: 0,
              period: '3 months',
            },
            delayed_handling_time: {
              rate: 0,
              excluded: {
                real_rate: 0.0171,
                real_value: 178,
              },
              value: 0,
              period: '3 months',
            },
            sales: {
              period: '3 months',
              completed: 10069,
            },
            cancellations: {
              rate: 0,
              excluded: {
                real_rate: 0.0067,
                real_value: 74,
              },
              value: 0,
              period: '3 months',
            },
          },
          protection_end_date: '2020-08-08T00:00:00.000-04:00',
          real_level: 'green_platinum',
          level_id: '5_green',
        },
        address: {
          zip_code: '1428',
          address: 'Ciudad De La Paz 1965',
          state: 'AR-C',
          city: 'Belgrano',
        },
      },
      price: 4999,
      currency_id: 'ARS',
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: 'buy_it_now',
      listing_type_id: 'gold_special',
      stop_time: '2040-05-15T04:00:00.000Z',
      condition: 'new',
      permalink: 'https://articulo.mercadolibre.com.ar/MLA-856774527-google-chromecast-3ra-generacion-2018-smart-tv-bulk-sin-caja-_JM',
      thumbnail: 'http://mla-s2-p.mlstatic.com/652479-MLA41889875358_052020-I.jpg',
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 708.9,
        rate: 70.17,
        currency_id: 'ARS',
      },
      address: {
        state_id: 'AR-C',
        state_name: 'Capital Federal',
        city_id: 'TUxBQkJFTDcyNTJa',
        city_name: 'Belgrano',
      },
      shipping: {
        free_shipping: true,
        mode: 'me2',
        tags: [
          'self_service_in',
          'mandatory_free_shipping',
        ],
        logistic_type: 'drop_off',
        store_pick_up: false,
      },
      seller_address: {
        id: '',
        comment: '',
        address_line: '',
        zip_code: '',
        country: {
          id: 'AR',
          name: 'Argentina',
        },
        state: {
          id: 'AR-C',
          name: 'Capital Federal',
        },
        city: {
          id: 'TUxBQkJFTDcyNTJa',
          name: 'Belgrano',
        },
        latitude: '',
        longitude: '',
      },
      attributes: [
        {
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          id: 'ALPHANUMERIC_MODEL',
          value_id: null,
          value_name: 'NC2-6A5',
          values: [
            {
              struct: null,
              source: 2860837171021627,
              id: null,
              name: 'NC2-6A5',
            },
          ],
          name: 'Modelo alfanumérico',
          value_struct: null,
          source: 2860837171021627,
        },
        {
          value_id: '52701',
          value_name: 'Google',
          value_struct: null,
          values: [
            {
              source: 2860837171021627,
              id: '52701',
              name: 'Google',
              struct: null,
            },
          ],
          attribute_group_name: 'Otros',
          id: 'BRAND',
          attribute_group_id: 'OTHERS',
          source: 2860837171021627,
          name: 'Marca',
        },
        {
          value_name: 'Nuevo',
          attribute_group_name: 'Otros',
          id: 'ITEM_CONDITION',
          value_id: '2230284',
          value_struct: null,
          values: [
            {
              id: '2230284',
              name: 'Nuevo',
              struct: null,
              source: 2860837171021627,
            },
          ],
          attribute_group_id: 'OTHERS',
          source: 2860837171021627,
          name: 'Condición del ítem',
        },
        {
          attribute_group_name: 'Otros',
          id: 'LINE',
          value_id: null,
          value_name: 'Chromecast',
          value_struct: null,
          values: [
            {
              id: null,
              name: 'Chromecast',
              struct: null,
              source: 2860837171021627,
            },
          ],
          attribute_group_id: 'OTHERS',
          source: 2860837171021627,
          name: 'Línea',
        },
        {
          value_name: 'Chromecast 3rd Generation',
          value_struct: null,
          values: [
            {
              struct: null,
              source: 2860837171021627,
              id: '7807620',
              name: 'Chromecast 3rd Generation',
            },
          ],
          attribute_group_id: 'OTHERS',
          id: 'MODEL',
          value_id: '7807620',
          attribute_group_name: 'Otros',
          source: 2860837171021627,
          name: 'Modelo',
        },
      ],
      original_price: null,
      category_id: 'MLA352001',
      official_store_id: null,
      domain_id: 'MLA-STREAMING_MEDIA_DEVICES',
      catalog_product_id: 'MLA13841393',
      tags: [
        'brand_verified',
        'catalog_listing_eligible',
        'good_quality_picture',
        'good_quality_thumbnail',
        'loyalty_discount_eligible',
        'immediate_payment',
        'cart_eligible',
        'shipping_guaranteed',
      ],
    },
    {
      id: 'MLA681084500',
      site_id: 'MLA',
      title: 'Google Chromecast 3 Smart Tv Hdmi Usb Nuevo Modelo Gtia ',
      seller: {
        id: 255318143,
        permalink: 'http://perfil.mercadolibre.com.ar/LMS-TIENDAVIRTUAL',
        registration_date: '2017-05-05T16:11:38.000-04:00',
        car_dealer: false,
        real_estate_agency: false,
        tags: [
          'normal',
          'user_info_verified',
          'credits_profile',
          'eshop',
          'messages_as_seller',
          'messages_as_buyer',
        ],
        eshop: {
          nick_name: 'LMS-TIENDAVIRTUAL',
          eshop_rubro: null,
          eshop_id: 258545,
          eshop_locations: [],
          site_id: 'MLA',
          eshop_logo_url: 'http://resources.mlstatic.com/eshops/255318143vda5ddc.png',
          eshop_status_id: 1,
          seller: 255318143,
          eshop_experience: 0,
        },
        seller_reputation: {
          transactions: {
            total: 42505,
            canceled: 1007,
            period: 'historic',
            ratings: {
              negative: 0.02,
              positive: 0.96,
              neutral: 0.02,
            },
            completed: 41498,
          },
          power_seller_status: 'platinum',
          metrics: {
            claims: {
              rate: 0.0159,
              value: 73,
              period: '3 months',
            },
            delayed_handling_time: {
              rate: 0.0006,
              value: 3,
              period: '3 months',
            },
            sales: {
              period: '3 months',
              completed: 4388,
            },
            cancellations: {
              rate: 0,
              value: 2,
              period: '3 months',
            },
          },
          level_id: '5_green',
        },
        address: {
          zip_code: '1071',
          address: 'Tacuari 239',
          state: 'AR-C',
          city: 'Monserrat',
        },
      },
      price: 4979,
      currency_id: 'ARS',
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: 'buy_it_now',
      listing_type_id: 'gold_special',
      stop_time: '2037-08-26T18:17:03.000Z',
      condition: 'new',
      permalink: 'https://articulo.mercadolibre.com.ar/MLA-681084500-google-chromecast-3-smart-tv-hdmi-usb-nuevo-modelo-gtia-_JM',
      thumbnail: 'http://mla-s1-p.mlstatic.com/810466-MLA31708543209_082019-I.jpg',
      accepts_mercadopago: true,
      installments: {
        quantity: 12,
        amount: 706.06,
        rate: 70.17,
        currency_id: 'ARS',
      },
      address: {
        state_id: 'AR-C',
        state_name: 'Capital Federal',
        city_id: 'TUxBQk1PTjUxOTJa',
        city_name: 'Monserrat',
      },
      shipping: {
        free_shipping: true,
        mode: 'me2',
        tags: [
          'self_service_in',
          'mandatory_free_shipping',
        ],
        logistic_type: 'cross_docking',
        store_pick_up: false,
      },
      seller_address: {
        id: '',
        comment: '',
        address_line: '',
        zip_code: '',
        country: {
          id: 'AR',
          name: 'Argentina',
        },
        state: {
          id: 'AR-C',
          name: 'Capital Federal',
        },
        city: {
          id: 'TUxBQk1PTjUxOTJa',
          name: 'Monserrat',
        },
        latitude: '',
        longitude: '',
      },
      attributes: [
        {
          value_name: 'chromecast3',
          value_struct: null,
          values: [
            {
              id: null,
              name: 'chromecast3',
              struct: null,
              source: 3376461333454861,
            },
          ],
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          id: 'ALPHANUMERIC_MODEL',
          value_id: null,
          name: 'Modelo alfanumérico',
          source: 3376461333454861,
        },
        {
          attribute_group_id: 'OTHERS',
          source: 1,
          id: 'BRAND',
          value_struct: null,
          value_name: 'Google',
          values: [
            {
              id: '52701',
              name: 'Google',
              struct: null,
              source: 1,
            },
          ],
          attribute_group_name: 'Otros',
          name: 'Marca',
          value_id: '52701',
        },
        {
          name: 'Condición del ítem',
          value_id: '2230284',
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          id: 'ITEM_CONDITION',
          value_name: 'Nuevo',
          value_struct: null,
          values: [
            {
              id: '2230284',
              name: 'Nuevo',
              struct: null,
              source: 1,
            },
          ],
          source: 1,
        },
        {
          attribute_group_id: 'OTHERS',
          attribute_group_name: 'Otros',
          source: 1,
          value_struct: null,
          values: [
            {
              id: null,
              name: 'Chromecast',
              struct: null,
              source: 1,
            },
          ],
          value_id: null,
          value_name: 'Chromecast',
          id: 'LINE',
          name: 'Línea',
        },
        {
          attribute_group_id: 'OTHERS',
          source: 1572,
          name: 'Modelo',
          value_id: '7807620',
          value_name: 'Chromecast 3rd Generation',
          value_struct: null,
          id: 'MODEL',
          values: [
            {
              id: '7807620',
              name: 'Chromecast 3rd Generation',
              struct: null,
              source: 1572,
            },
          ],
          attribute_group_name: 'Otros',
        },
      ],
      original_price: null,
      category_id: 'MLA352001',
      official_store_id: null,
      domain_id: 'MLA-STREAMING_MEDIA_DEVICES',
      catalog_product_id: 'MLA13841392',
      tags: [
        'brand_verified',
        'catalog_listing_eligible',
        'good_quality_picture',
        'good_quality_thumbnail',
        'loyalty_discount_eligible',
        'immediate_payment',
        'cart_eligible',
        'shipping_guaranteed',
      ],
    },
  ],
  secondary_results: [],
  related_results: [],
  sort: {
    id: 'relevance',
    name: 'Más relevantes',
  },
  available_sorts: [
    {
      id: 'price_asc',
      name: 'Menor precio',
    },
    {
      id: 'price_desc',
      name: 'Mayor precio',
    },
  ],
  filters: [
    {
      id: 'category',
      name: 'Categorías',
      type: 'text',
      values: [
        {
          id: 'MLA352001',
          name: 'Media Streaming',
          path_from_root: [
            {
              id: 'MLA1000',
              name: 'Electrónica, Audio y Video',
            },
            {
              id: 'MLA352001',
              name: 'Media Streaming',
            },
          ],
        },
      ],
    },
    {
      id: 'BRAND',
      name: 'Marca',
      type: 'STRING',
      values: [
        {
          id: '52701',
          name: 'Google',
        },
      ],
    },
  ],
  available_filters: [
    {
      id: 'official_store',
      name: 'Tiendas oficiales',
      type: 'text',
      values: [
        {
          id: 'all',
          name: 'Todas las tiendas oficiales',
          results: 3,
        },
      ],
    },
    {
      id: 'discount',
      name: 'Descuentos',
      type: 'range',
      values: [
        {
          id: '10-100',
          name: 'Desde 10% off',
          results: 7,
        },
        {
          id: '20-100',
          name: 'Desde 20% off',
          results: 4,
        },
        {
          id: '30-100',
          name: 'Desde 30% off',
          results: 1,
        },
      ],
    },
    {
      id: 'state',
      name: 'Ubicación',
      type: 'text',
      values: [
        {
          id: 'TUxBUENBUGw3M2E1',
          name: 'Capital Federal',
          results: 144,
        },
        {
          id: 'TUxBUEdSQWVmNTVm',
          name: 'Bs.As. G.B.A. Oeste',
          results: 32,
        },
        {
          id: 'TUxBUEdSQWU4ZDkz',
          name: 'Bs.As. G.B.A. Norte',
          results: 29,
        },
        {
          id: 'TUxBUFNBTmU5Nzk2',
          name: 'Santa Fe',
          results: 22,
        },
        {
          id: 'TUxBUEdSQXJlMDNm',
          name: 'Bs.As. G.B.A. Sur',
          results: 19,
        },
        {
          id: 'TUxBUENPUmFkZGIw',
          name: 'Córdoba',
          results: 18,
        },
        {
          id: 'TUxBUENPU2ExMmFkMw',
          name: 'Bs.As. Costa Atlántica',
          results: 13,
        },
        {
          id: 'TUxBUFpPTmFpbnRl',
          name: 'Buenos Aires Interior',
          results: 9,
        },
        {
          id: 'TUxBUFRVQ244NmM3',
          name: 'Tucumán',
          results: 6,
        },
        {
          id: 'TUxBUEVOVHMzNTdm',
          name: 'Entre Ríos',
          results: 4,
        },
        {
          id: 'TUxBUE1FTmE5OWQ4',
          name: 'Mendoza',
          results: 3,
        },
        {
          id: 'TUxBUE1JU3MzNjIx',
          name: 'Misiones',
          results: 3,
        },
        {
          id: 'TUxBUE5FVW4xMzMzNQ',
          name: 'Neuquén',
          results: 3,
        },
        {
          id: 'TUxBUENIQW8xMTNhOA',
          name: 'Chaco',
          results: 3,
        },
        {
          id: 'TUxBUENBVGFiY2Fm',
          name: 'Catamarca',
          results: 2,
        },
        {
          id: 'TUxBUEpVSnk3YmUz',
          name: 'Jujuy',
          results: 2,
        },
        {
          id: 'TUxBUFLNT29iZmZm',
          name: 'Río Negro',
          results: 2,
        },
        {
          id: 'TUxBUFNBTm5lYjU4',
          name: 'San Juan',
          results: 2,
        },
        {
          id: 'TUxBUFNBTm9lOTlk',
          name: 'Santiago del Estero',
          results: 2,
        },
        {
          id: 'TUxBUFNBTno3ZmY5',
          name: 'Santa Cruz',
          results: 2,
        },
        {
          id: 'TUxBUENIVXQxNDM1MQ',
          name: 'Chubut',
          results: 1,
        },
        {
          id: 'TUxBUENPUnM5MjI0',
          name: 'Corrientes',
          results: 1,
        },
        {
          id: 'TUxBUEZPUmE1OTk5',
          name: 'Formosa',
          results: 1,
        },
        {
          id: 'TUxBUExBWmE1OWMy',
          name: 'La Pampa',
          results: 1,
        },
        {
          id: 'TUxBUExBWmEyNzY0',
          name: 'La Rioja',
          results: 1,
        },
        {
          id: 'TUxBUFNBTGFjMTJi',
          name: 'Salta',
          results: 1,
        },
        {
          id: 'TUxBUFNBTnM0ZTcz',
          name: 'San Luis',
          results: 1,
        },
      ],
    },
    {
      id: 'price',
      name: 'Precio',
      type: 'range',
      values: [
        {
          id: '*-5500.0',
          name: 'Hasta $ 5.500',
          results: 74,
        },
        {
          id: '5500.0-7000.0',
          name: '$5.500 a $7.000',
          results: 130,
        },
        {
          id: '7000.0-*',
          name: 'Más de $7.000',
          results: 109,
        },
      ],
    },
    {
      id: 'accepts_mercadopago',
      name: 'Filtro por MercadoPago',
      type: 'boolean',
      values: [
        {
          id: 'yes',
          name: 'Con MercadoPago',
          results: 313,
        },
      ],
    },
    {
      id: 'installments',
      name: 'Pago',
      type: 'text',
      values: [
        {
          id: 'yes',
          name: 'En cuotas',
          results: 313,
        },
        {
          id: 'no_interest',
          name: 'Sin interés',
          results: 43,
        },
      ],
    },
    {
      id: 'shipping',
      name: 'Tipo de entrega',
      type: 'text',
      values: [
        {
          id: 'mercadoenvios',
          name: 'Con envío',
          results: 311,
        },
        {
          id: 'fulfillment',
          name: 'Full',
          results: 6,
        },
      ],
    },
    {
      id: 'power_seller',
      name: 'Filtro por calidad de vendedores',
      type: 'boolean',
      values: [
        {
          id: 'yes',
          name: 'Mejores vendedores',
          results: 121,
        },
      ],
    },
    {
      id: 'since',
      name: 'Filtro por fecha de comienzo',
      type: 'text',
      values: [
        {
          id: 'today',
          name: 'Publicados hoy',
          results: 5,
        },
      ],
    },
    {
      id: 'has_video',
      name: 'Filtro por publicaciones con video',
      type: 'boolean',
      values: [
        {
          id: 'yes',
          name: 'Publicaciones con video',
          results: 38,
        },
      ],
    },
    {
      id: 'has_pictures',
      name: 'Filtro por publicaciones con imágenes',
      type: 'boolean',
      values: [
        {
          id: 'yes',
          name: 'Con fotos',
          results: 313,
        },
      ],
    },
    {
      id: 'shipping_cost',
      name: 'Costo de envío',
      type: 'text',
      values: [
        {
          id: 'free',
          name: 'Gratis',
          results: 238,
        },
      ],
    },
    {
      id: 'shipping_quarantine',
      name: 'Tipo de entrega',
      type: 'text',
      values: [
        {
          id: 'guaranteed_delivery',
          name: 'Envío con normalidad',
          results: 220,
        },
      ],
    },
    {
      id: 'ITEM_CONDITION',
      name: 'Condición',
      type: 'STRING',
      values: [
        {
          id: '2230284',
          name: 'Nuevo',
          results: 260,
        },
        {
          id: '2230581',
          name: 'Usado',
          results: 52,
        },
        {
          id: '2230582',
          name: 'Reacondicionado',
          results: 1,
        },
      ],
    },
    {
      id: 'MODEL',
      name: 'Modelo',
      type: 'STRING',
      values: [
        {
          id: '7807620',
          name: 'Chromecast 3rd Generation',
          results: 193,
        },
        {
          id: '7807621',
          name: 'Chromecast 2nd Generation',
          results: 53,
        },
        {
          id: '402606',
          name: 'Chromecast Ultra',
          results: 9,
        },
        {
          id: '7807622',
          name: 'Chromecast 1st Generation',
          results: 7,
        },
        {
          id: '49506',
          name: '3',
          results: 3,
        },
        {
          id: '34004',
          name: 'Ultra',
          results: 1,
        },
        {
          id: '168517',
          name: 'Chromecast Audio',
          results: 1,
        },
      ],
    },
  ],
};

export default searchResponseMock;
